#### ReflexAutoban Configuration ######################################
#
#   Welcome here! Looks like you want to change something, am
# I right? Before doing so, please note one thing: all the
# settings were tested a lot to work properly. If ReflexAutoban breaks
# after you touched anything, it's YOUR fault.
#
#   For any configuration assistance please private message
# DarksideCode on Spigot, open an issue at https://g.reflex.rip/bug
# or write us in Discord: https://g.reflex.rip/discord
#
#   PLEASE REFRAIN FROM TOUCHING ANYTHING WITHOUT SERIOUS REASONS TO!
#
#   Useful links:
#
#       1. Reflex on Spigot:
#          --> https://g.reflex.rip/spigot
#
#       2. Reflex Discord:
#          --> https://g.reflex.rip/discord
#
#       3. ReflexAutoban on Spigot:
#          --> https://www.spigotmc.org/resources/31306/
#
#       4. ReflexAutoban on GitHub:
#          --> https://github.com/MeGysssTaa/ReflexAutoban
#
#   With love, Reflex Development Team.
#   © reflex.rip, 2016-2019.
#
########################################################################

# Where should the data files be saved? Data files contain info
# about players banned, logs, etc. (see overview).
#
# %default_data_folder% will be replaced with '/{your_server_folder}/plugins/ReflexAutoban/'
#
# If you have a BungeeCord network on a single VPS, and don't
# want to use MySQL, make sure to specify the same working
# directory for all the servers!
working_directory: '%default_data_folder%'

# If enabled, ReflexAutoban will write its logs in special files saved in
# {working_directory}/logs and named in format DD-MM-YYYY.log.
# ReflexAutoban makes one log per day. This means one log will contain
# everything happened in a day. 24 hours later, there will be
# a new file created with a new date containing the events of a new day
make_logs: true

# Enable developer mode? This will let ReflexAutoban log
# debug messages and print full stack traces and errors
dev_mode: false

# Messages customization
lang:

  # ReflexAutoban prefix to display in its messages
  prefix: "&9&l「&r&bRAB&9&l」&r"

  # The message that is displayed at the end of ban waves
  ban_wave_end: "  &c&l&nREFLEX CHEAT DETECTION&r%break%
        &b%players_banned%&r cheaters have been banned for interrupting fair%break%
        players' gameplay in this ban wave. Let the justice prevail!"

  # Messages related to Reflex Autoban subcommands
  commands:

    # Messages related to the '/rab banwave' command
    ban_wave:

      # The description of the '/rab banwave' command displayed in '/rab help'
      description: 'Ban wave monitoring and management'

      # Sent to the sender of the '/reflex banwave run' command
      run: 'Forcing the ban wave to run as fast as it can!'

      # Sent to the sender of the '/reflex banwave info' command.
      # Gives sender the neccessary info related to the current ban wave
      info: 'Next regular schedule: &9in %time%%break%
      &rPlayers (&9%players_number%&r): &7%players_list%'

      # Sent to the sender of the '/reflex banwave addplayer' command
      addplayer: 'Added player &9%player%&r to the ban wave'

      # Sent to the sender of the '/reflex banwave removeplayer' command
      removeplayer: 'Removed player &9%player%&r from the ban wave'

      # Sent to the sender of the '/reflex banwave clear' command
      clear: 'Cleared the ban wave'

# Hide ReflexAutoban commands from players who haven't got the appropriate permissinons?
hide: true

# How often should the ban wave run (in minutes)?
# Please note that the purpose of any anticheat is to prevent
# cheaters from ruining gameplay of legitimate players. This
# means that detected hackers should be removed from the server
# as quickly as possible. Using high periods is very undesirable
# at least because then it will allow hackers to interrupt many
# games before they get banned, and then switch alt just within seconds.
# (!) The concept of ban wave itself is NOT recommended if you want
# your server to be simply clean without unnecessary show-offs
ban_wave_period: 15

# Map of Reflex check names to their PK weights. The numbers are
# basically how many potential kicks will ReflexAutoban score to
# a player each time they get 'kicked' by Reflex according to the
# weight assigned to that check
weights:

  # How many PKs will a player score in case of a Reflex kick for KillAura?
  killaura: 1

  # How many PKs will a player score in case of a Reflex kick for Criticals?
  criticals: 2

  # How many PKs will a player score in case of a Reflex kick for AntiKnockback?
  antiknockback: 2

  # How many PKs will a player score in case of a Reflex kick for BlockActions?
  blockactions: 2

  # How many PKs will a player score in case of a Reflex kick for BadPackets?
  badpackets: 1

  # How many PKs will a player score in case of a Reflex kick for InvActions?
  invactions: 1

  # How many PKs will a player score in case of a Reflex kick for VehicleMove?
  vehiclemove: 2

  # How many PKs will a player score in case of a Reflex kick for ElytraMove?
  elytramove: 2

# Used when calculating the number of PKs to score after a potential kick.
# If at the moment of new PK there have been less than {double_weight_rate}
# seconds from the previous one, the number of PKs scored will be doubled.
# Used to ban blatant cheaters who get kicked very often slightly faster
double_weight_rate: 30

# Enable this if you want Reflex's machine learning check to ban faster
# in case it's {double_weight_confidence}+% sure that a player is cheating.
# This works by checking the "conviction" percent shown in Reflex verbose
# after getting flagged by the machine learning check. If that percent is
# greater than or equal to the number specified below, the number of PKs
# ReflexAutoban will score will be doubled. (!) RECOMMENDED AT LEAST 75!
# Note that this setting will be ignored if double_weight_rate is triggered
double_weight_confidence: 9999

# Global PKs reducement schedule settings
pk_decay:

  # How often (in minutes) should players' number of PKs reduce by one?
  # For example, if set to 5, and a player gets 1 (one) PK, then that PK
  # will be removed and the total number of PKs for that player will be
  # set to 0 after five minutes. NOTE: no decimals (e.g. `2.5`) allowed!
  period: 15

  # If a player has got any potential kicks in the last {penalty} minutes,
  # then they are excluded from decaying, and their number of PKs is kept
  # as is. This is needed to avoid forgiving new/fresh potential kicks
  penalty: 2

# Actions that are taken at players who reach specific numbers of PKs (Potential Kicks - see overview for details).
# See the overview page for details
actions:

  # Executed at all players who were in the ban wave
  # list at the moment when the ban wave ran.
  # WARNING: ALL ACTIONS HERE ARE RAN ASYNC BY DEFAULT!!!
  #          IF SYNCHRONOUS RUN IS DESIRED, PLEASE ADD A
  #          '@sync' ARGUMENT IN ALL ACTIONS STRINGS BELOW
  #          OR INSERT AN 'ALL_SYNC' ACTION AT THE TOP!
  ban_wave:
  - "SAVE_LOGS %player% %id%"
  - "RUN_COMMAND reflex ban %player% 7d
  &c&lYour account is suspended.&r%break%%break%
  The &b&lREFLEX ANTICHEATING SYSTEM&r has classified you as a possible cheater &7(%id%)&r.%break%
  Please contact us if you believe that this ban is unfair.%break%%break%&7
  %date%"

  # Executed when a player scores 3 or more PKs. See overview
  # if you want to add players with N+ PKs to the ban wave.
  3:
  - "ALL_ASYNC"
  - "IGNORE_NEXT %player%"
  - "SAVE_LOGS %player% %id%"
  - "WAIT $rnd(5,10)"
  - "PLAY_BAN_ANIMATION 0 %player%"
  - "RUN_COMMAND reflex ban %player% 7d
  &c&lYour account is suspended.&r%break%%break%
  The &b&lREFLEX ANTICHEATING SYSTEM&r has classified you as a possible cheater &7(%id%)&r.%break%
  Please contact us if you believe that this ban is unfair.%break%%break%&7
  %date%"